// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: com/toutiao/melon/rpc/master.proto

package com.toutiao.melon.rpc;

/**
 * Protobuf type {@code com.toutiao.melon.rpc.ManageJobRequest}
 */
public  final class ManageJobRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.toutiao.melon.rpc.ManageJobRequest)
    ManageJobRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ManageJobRequest.newBuilder() to construct.
  private ManageJobRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ManageJobRequest() {
  }

  @Override
  @SuppressWarnings({"unused"})
  protected Object newInstance(
      UnusedPrivateParameter unused) {
    return new ManageJobRequest();
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ManageJobRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            ManageJobRequestMetadata.Builder subBuilder = null;
            if (dataCase_ == 1) {
              subBuilder = ((ManageJobRequestMetadata) data_).toBuilder();
            }
            data_ =
                input.readMessage(ManageJobRequestMetadata.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((ManageJobRequestMetadata) data_);
              data_ = subBuilder.buildPartial();
            }
            dataCase_ = 1;
            break;
          }
          case 18: {
            dataCase_ = 2;
            data_ = input.readBytes();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return Master.internal_static_com_toutiao_melon_rpc_ManageJobRequest_descriptor;
  }

  @Override
  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return Master.internal_static_com_toutiao_melon_rpc_ManageJobRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            ManageJobRequest.class, Builder.class);
  }

  private int dataCase_ = 0;
  private Object data_;
  public enum DataCase
      implements com.google.protobuf.Internal.EnumLite,
          InternalOneOfEnum {
    METADATA(1),
    JAR_BYTES(2),
    DATA_NOT_SET(0);
    private final int value;
    private DataCase(int value) {
      this.value = value;
    }
    /**
     * @param value The number of the enum to look for.
     * @return The enum associated with the given number.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @Deprecated
    public static DataCase valueOf(int value) {
      return forNumber(value);
    }

    public static DataCase forNumber(int value) {
      switch (value) {
        case 1: return METADATA;
        case 2: return JAR_BYTES;
        case 0: return DATA_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  public DataCase
  getDataCase() {
    return DataCase.forNumber(
        dataCase_);
  }

  public static final int METADATA_FIELD_NUMBER = 1;
  /**
   * <pre>
   * First message is metadata then jar_bytes if needed
   * </pre>
   *
   * <code>.com.toutiao.melon.rpc.ManageJobRequestMetadata metadata = 1;</code>
   * @return Whether the metadata field is set.
   */
  public boolean hasMetadata() {
    return dataCase_ == 1;
  }
  /**
   * <pre>
   * First message is metadata then jar_bytes if needed
   * </pre>
   *
   * <code>.com.toutiao.melon.rpc.ManageJobRequestMetadata metadata = 1;</code>
   * @return The metadata.
   */
  public ManageJobRequestMetadata getMetadata() {
    if (dataCase_ == 1) {
       return (ManageJobRequestMetadata) data_;
    }
    return ManageJobRequestMetadata.getDefaultInstance();
  }
  /**
   * <pre>
   * First message is metadata then jar_bytes if needed
   * </pre>
   *
   * <code>.com.toutiao.melon.rpc.ManageJobRequestMetadata metadata = 1;</code>
   */
  public ManageJobRequestMetadataOrBuilder getMetadataOrBuilder() {
    if (dataCase_ == 1) {
       return (ManageJobRequestMetadata) data_;
    }
    return ManageJobRequestMetadata.getDefaultInstance();
  }

  public static final int JAR_BYTES_FIELD_NUMBER = 2;
  /**
   * <code>bytes jar_bytes = 2;</code>
   * @return The jarBytes.
   */
  public com.google.protobuf.ByteString getJarBytes() {
    if (dataCase_ == 2) {
      return (com.google.protobuf.ByteString) data_;
    }
    return com.google.protobuf.ByteString.EMPTY;
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (dataCase_ == 1) {
      output.writeMessage(1, (ManageJobRequestMetadata) data_);
    }
    if (dataCase_ == 2) {
      output.writeBytes(
          2, (com.google.protobuf.ByteString) data_);
    }
    unknownFields.writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (dataCase_ == 1) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, (ManageJobRequestMetadata) data_);
    }
    if (dataCase_ == 2) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(
            2, (com.google.protobuf.ByteString) data_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof ManageJobRequest)) {
      return super.equals(obj);
    }
    ManageJobRequest other = (ManageJobRequest) obj;

    if (!getDataCase().equals(other.getDataCase())) return false;
    switch (dataCase_) {
      case 1:
        if (!getMetadata()
            .equals(other.getMetadata())) return false;
        break;
      case 2:
        if (!getJarBytes()
            .equals(other.getJarBytes())) return false;
        break;
      case 0:
      default:
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    switch (dataCase_) {
      case 1:
        hash = (37 * hash) + METADATA_FIELD_NUMBER;
        hash = (53 * hash) + getMetadata().hashCode();
        break;
      case 2:
        hash = (37 * hash) + JAR_BYTES_FIELD_NUMBER;
        hash = (53 * hash) + getJarBytes().hashCode();
        break;
      case 0:
      default:
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static ManageJobRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ManageJobRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ManageJobRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ManageJobRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ManageJobRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ManageJobRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ManageJobRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ManageJobRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static ManageJobRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static ManageJobRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static ManageJobRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ManageJobRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(ManageJobRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.toutiao.melon.rpc.ManageJobRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.toutiao.melon.rpc.ManageJobRequest)
      ManageJobRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Master.internal_static_com_toutiao_melon_rpc_ManageJobRequest_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Master.internal_static_com_toutiao_melon_rpc_ManageJobRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ManageJobRequest.class, Builder.class);
    }

    // Construct using com.toutiao.melon.rpc.ManageJobRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @Override
    public Builder clear() {
      super.clear();
      dataCase_ = 0;
      data_ = null;
      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return Master.internal_static_com_toutiao_melon_rpc_ManageJobRequest_descriptor;
    }

    @Override
    public ManageJobRequest getDefaultInstanceForType() {
      return ManageJobRequest.getDefaultInstance();
    }

    @Override
    public ManageJobRequest build() {
      ManageJobRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public ManageJobRequest buildPartial() {
      ManageJobRequest result = new ManageJobRequest(this);
      if (dataCase_ == 1) {
        if (metadataBuilder_ == null) {
          result.data_ = data_;
        } else {
          result.data_ = metadataBuilder_.build();
        }
      }
      if (dataCase_ == 2) {
        result.data_ = data_;
      }
      result.dataCase_ = dataCase_;
      onBuilt();
      return result;
    }

    @Override
    public Builder clone() {
      return super.clone();
    }
    @Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.setField(field, value);
    }
    @Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.addRepeatedField(field, value);
    }
    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof ManageJobRequest) {
        return mergeFrom((ManageJobRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(ManageJobRequest other) {
      if (other == ManageJobRequest.getDefaultInstance()) return this;
      switch (other.getDataCase()) {
        case METADATA: {
          mergeMetadata(other.getMetadata());
          break;
        }
        case JAR_BYTES: {
          setJarBytes(other.getJarBytes());
          break;
        }
        case DATA_NOT_SET: {
          break;
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      ManageJobRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (ManageJobRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int dataCase_ = 0;
    private Object data_;
    public DataCase
        getDataCase() {
      return DataCase.forNumber(
          dataCase_);
    }

    public Builder clearData() {
      dataCase_ = 0;
      data_ = null;
      onChanged();
      return this;
    }


    private com.google.protobuf.SingleFieldBuilderV3<
        ManageJobRequestMetadata, ManageJobRequestMetadata.Builder, ManageJobRequestMetadataOrBuilder> metadataBuilder_;
    /**
     * <pre>
     * First message is metadata then jar_bytes if needed
     * </pre>
     *
     * <code>.com.toutiao.melon.rpc.ManageJobRequestMetadata metadata = 1;</code>
     * @return Whether the metadata field is set.
     */
    public boolean hasMetadata() {
      return dataCase_ == 1;
    }
    /**
     * <pre>
     * First message is metadata then jar_bytes if needed
     * </pre>
     *
     * <code>.com.toutiao.melon.rpc.ManageJobRequestMetadata metadata = 1;</code>
     * @return The metadata.
     */
    public ManageJobRequestMetadata getMetadata() {
      if (metadataBuilder_ == null) {
        if (dataCase_ == 1) {
          return (ManageJobRequestMetadata) data_;
        }
        return ManageJobRequestMetadata.getDefaultInstance();
      } else {
        if (dataCase_ == 1) {
          return metadataBuilder_.getMessage();
        }
        return ManageJobRequestMetadata.getDefaultInstance();
      }
    }
    /**
     * <pre>
     * First message is metadata then jar_bytes if needed
     * </pre>
     *
     * <code>.com.toutiao.melon.rpc.ManageJobRequestMetadata metadata = 1;</code>
     */
    public Builder setMetadata(ManageJobRequestMetadata value) {
      if (metadataBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        data_ = value;
        onChanged();
      } else {
        metadataBuilder_.setMessage(value);
      }
      dataCase_ = 1;
      return this;
    }
    /**
     * <pre>
     * First message is metadata then jar_bytes if needed
     * </pre>
     *
     * <code>.com.toutiao.melon.rpc.ManageJobRequestMetadata metadata = 1;</code>
     */
    public Builder setMetadata(
        ManageJobRequestMetadata.Builder builderForValue) {
      if (metadataBuilder_ == null) {
        data_ = builderForValue.build();
        onChanged();
      } else {
        metadataBuilder_.setMessage(builderForValue.build());
      }
      dataCase_ = 1;
      return this;
    }
    /**
     * <pre>
     * First message is metadata then jar_bytes if needed
     * </pre>
     *
     * <code>.com.toutiao.melon.rpc.ManageJobRequestMetadata metadata = 1;</code>
     */
    public Builder mergeMetadata(ManageJobRequestMetadata value) {
      if (metadataBuilder_ == null) {
        if (dataCase_ == 1 &&
            data_ != ManageJobRequestMetadata.getDefaultInstance()) {
          data_ = ManageJobRequestMetadata.newBuilder((ManageJobRequestMetadata) data_)
              .mergeFrom(value).buildPartial();
        } else {
          data_ = value;
        }
        onChanged();
      } else {
        if (dataCase_ == 1) {
          metadataBuilder_.mergeFrom(value);
        }
        metadataBuilder_.setMessage(value);
      }
      dataCase_ = 1;
      return this;
    }
    /**
     * <pre>
     * First message is metadata then jar_bytes if needed
     * </pre>
     *
     * <code>.com.toutiao.melon.rpc.ManageJobRequestMetadata metadata = 1;</code>
     */
    public Builder clearMetadata() {
      if (metadataBuilder_ == null) {
        if (dataCase_ == 1) {
          dataCase_ = 0;
          data_ = null;
          onChanged();
        }
      } else {
        if (dataCase_ == 1) {
          dataCase_ = 0;
          data_ = null;
        }
        metadataBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * First message is metadata then jar_bytes if needed
     * </pre>
     *
     * <code>.com.toutiao.melon.rpc.ManageJobRequestMetadata metadata = 1;</code>
     */
    public ManageJobRequestMetadata.Builder getMetadataBuilder() {
      return getMetadataFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * First message is metadata then jar_bytes if needed
     * </pre>
     *
     * <code>.com.toutiao.melon.rpc.ManageJobRequestMetadata metadata = 1;</code>
     */
    public ManageJobRequestMetadataOrBuilder getMetadataOrBuilder() {
      if ((dataCase_ == 1) && (metadataBuilder_ != null)) {
        return metadataBuilder_.getMessageOrBuilder();
      } else {
        if (dataCase_ == 1) {
          return (ManageJobRequestMetadata) data_;
        }
        return ManageJobRequestMetadata.getDefaultInstance();
      }
    }
    /**
     * <pre>
     * First message is metadata then jar_bytes if needed
     * </pre>
     *
     * <code>.com.toutiao.melon.rpc.ManageJobRequestMetadata metadata = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        ManageJobRequestMetadata, ManageJobRequestMetadata.Builder, ManageJobRequestMetadataOrBuilder>
        getMetadataFieldBuilder() {
      if (metadataBuilder_ == null) {
        if (!(dataCase_ == 1)) {
          data_ = ManageJobRequestMetadata.getDefaultInstance();
        }
        metadataBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            ManageJobRequestMetadata, ManageJobRequestMetadata.Builder, ManageJobRequestMetadataOrBuilder>(
                (ManageJobRequestMetadata) data_,
                getParentForChildren(),
                isClean());
        data_ = null;
      }
      dataCase_ = 1;
      onChanged();;
      return metadataBuilder_;
    }

    /**
     * <code>bytes jar_bytes = 2;</code>
     * @return The jarBytes.
     */
    public com.google.protobuf.ByteString getJarBytes() {
      if (dataCase_ == 2) {
        return (com.google.protobuf.ByteString) data_;
      }
      return com.google.protobuf.ByteString.EMPTY;
    }
    /**
     * <code>bytes jar_bytes = 2;</code>
     * @param value The jarBytes to set.
     * @return This builder for chaining.
     */
    public Builder setJarBytes(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  dataCase_ = 2;
      data_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bytes jar_bytes = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearJarBytes() {
      if (dataCase_ == 2) {
        dataCase_ = 0;
        data_ = null;
        onChanged();
      }
      return this;
    }
    @Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.toutiao.melon.rpc.ManageJobRequest)
  }

  // @@protoc_insertion_point(class_scope:com.toutiao.melon.rpc.ManageJobRequest)
  private static final ManageJobRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new ManageJobRequest();
  }

  public static ManageJobRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ManageJobRequest>
      PARSER = new com.google.protobuf.AbstractParser<ManageJobRequest>() {
    @Override
    public ManageJobRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ManageJobRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ManageJobRequest> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<ManageJobRequest> getParserForType() {
    return PARSER;
  }

  @Override
  public ManageJobRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

