// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: com/toutiao/melon/rpc/master.proto

package com.toutiao.melon.rpc;

public interface ManageJobRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.toutiao.melon.rpc.ManageJobRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * First message is metadata then jar_bytes if needed
   * </pre>
   *
   * <code>.com.toutiao.melon.rpc.ManageJobRequestMetadata metadata = 1;</code>
   * @return Whether the metadata field is set.
   */
  boolean hasMetadata();
  /**
   * <pre>
   * First message is metadata then jar_bytes if needed
   * </pre>
   *
   * <code>.com.toutiao.melon.rpc.ManageJobRequestMetadata metadata = 1;</code>
   * @return The metadata.
   */
  ManageJobRequestMetadata getMetadata();
  /**
   * <pre>
   * First message is metadata then jar_bytes if needed
   * </pre>
   *
   * <code>.com.toutiao.melon.rpc.ManageJobRequestMetadata metadata = 1;</code>
   */
  ManageJobRequestMetadataOrBuilder getMetadataOrBuilder();

  /**
   * <code>bytes jar_bytes = 2;</code>
   * @return The jarBytes.
   */
  com.google.protobuf.ByteString getJarBytes();

  public ManageJobRequest.DataCase getDataCase();
}
