// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: com/toutiao/melon/rpc/master.proto

package com.toutiao.melon.rpc;

public interface ManageJobRequestMetadataOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.toutiao.melon.rpc.ManageJobRequestMetadata)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.com.toutiao.melon.rpc.ManageJobRequestMetadata.RequestType request_type = 1;</code>
   * @return The enum numeric value on the wire for requestType.
   */
  int getRequestTypeValue();
  /**
   * <code>.com.toutiao.melon.rpc.ManageJobRequestMetadata.RequestType request_type = 1;</code>
   * @return The requestType.
   */
  ManageJobRequestMetadata.RequestType getRequestType();

  /**
   * <code>string job_name = 2;</code>
   * @return The jobName.
   */
  String getJobName();
  /**
   * <code>string job_name = 2;</code>
   * @return The bytes for jobName.
   */
  com.google.protobuf.ByteString
      getJobNameBytes();
}
