// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: com/toutiao/melon/rpc/master.proto

package com.toutiao.melon.rpc;

/**
 * Protobuf type {@code com.toutiao.melon.rpc.ManageJobRequestMetadata}
 */
public  final class ManageJobRequestMetadata extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.toutiao.melon.rpc.ManageJobRequestMetadata)
    ManageJobRequestMetadataOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ManageJobRequestMetadata.newBuilder() to construct.
  private ManageJobRequestMetadata(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ManageJobRequestMetadata() {
    requestType_ = 0;
    jobName_ = "";
  }

  @Override
  @SuppressWarnings({"unused"})
  protected Object newInstance(
      UnusedPrivateParameter unused) {
    return new ManageJobRequestMetadata();
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ManageJobRequestMetadata(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {
            int rawValue = input.readEnum();

            requestType_ = rawValue;
            break;
          }
          case 18: {
            String s = input.readStringRequireUtf8();

            jobName_ = s;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return Master.internal_static_com_toutiao_melon_rpc_ManageJobRequestMetadata_descriptor;
  }

  @Override
  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return Master.internal_static_com_toutiao_melon_rpc_ManageJobRequestMetadata_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            ManageJobRequestMetadata.class, Builder.class);
  }

  /**
   * Protobuf enum {@code com.toutiao.melon.rpc.ManageJobRequestMetadata.RequestType}
   */
  public enum RequestType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>START_Job = 0;</code>
     */
    START_Job(0),
    /**
     * <code>STOP_Job = 1;</code>
     */
    STOP_Job(1),
    /**
     * <code>QUERY_RUNNING_Job = 2;</code>
     */
    QUERY_RUNNING_Job(2),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>START_Job = 0;</code>
     */
    public static final int START_Job_VALUE = 0;
    /**
     * <code>STOP_Job = 1;</code>
     */
    public static final int STOP_Job_VALUE = 1;
    /**
     * <code>QUERY_RUNNING_Job = 2;</code>
     */
    public static final int QUERY_RUNNING_Job_VALUE = 2;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @Deprecated
    public static RequestType valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static RequestType forNumber(int value) {
      switch (value) {
        case 0: return START_Job;
        case 1: return STOP_Job;
        case 2: return QUERY_RUNNING_Job;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<RequestType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        RequestType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<RequestType>() {
            public RequestType findValueByNumber(int number) {
              return RequestType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return ManageJobRequestMetadata.getDescriptor().getEnumTypes().get(0);
    }

    private static final RequestType[] VALUES = values();

    public static RequestType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private RequestType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:com.toutiao.melon.rpc.ManageJobRequestMetadata.RequestType)
  }

  public static final int REQUEST_TYPE_FIELD_NUMBER = 1;
  private int requestType_;
  /**
   * <code>.com.toutiao.melon.rpc.ManageJobRequestMetadata.RequestType request_type = 1;</code>
   * @return The enum numeric value on the wire for requestType.
   */
  public int getRequestTypeValue() {
    return requestType_;
  }
  /**
   * <code>.com.toutiao.melon.rpc.ManageJobRequestMetadata.RequestType request_type = 1;</code>
   * @return The requestType.
   */
  public RequestType getRequestType() {
    @SuppressWarnings("deprecation")
    RequestType result = RequestType.valueOf(requestType_);
    return result == null ? RequestType.UNRECOGNIZED : result;
  }

  public static final int JOB_NAME_FIELD_NUMBER = 2;
  private volatile Object jobName_;
  /**
   * <code>string job_name = 2;</code>
   * @return The jobName.
   */
  public String getJobName() {
    Object ref = jobName_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      jobName_ = s;
      return s;
    }
  }
  /**
   * <code>string job_name = 2;</code>
   * @return The bytes for jobName.
   */
  public com.google.protobuf.ByteString
      getJobNameBytes() {
    Object ref = jobName_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      jobName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (requestType_ != RequestType.START_Job.getNumber()) {
      output.writeEnum(1, requestType_);
    }
    if (!getJobNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, jobName_);
    }
    unknownFields.writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (requestType_ != RequestType.START_Job.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(1, requestType_);
    }
    if (!getJobNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, jobName_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof ManageJobRequestMetadata)) {
      return super.equals(obj);
    }
    ManageJobRequestMetadata other = (ManageJobRequestMetadata) obj;

    if (requestType_ != other.requestType_) return false;
    if (!getJobName()
        .equals(other.getJobName())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + REQUEST_TYPE_FIELD_NUMBER;
    hash = (53 * hash) + requestType_;
    hash = (37 * hash) + JOB_NAME_FIELD_NUMBER;
    hash = (53 * hash) + getJobName().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static ManageJobRequestMetadata parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ManageJobRequestMetadata parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ManageJobRequestMetadata parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ManageJobRequestMetadata parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ManageJobRequestMetadata parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ManageJobRequestMetadata parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ManageJobRequestMetadata parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ManageJobRequestMetadata parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static ManageJobRequestMetadata parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static ManageJobRequestMetadata parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static ManageJobRequestMetadata parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ManageJobRequestMetadata parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(ManageJobRequestMetadata prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.toutiao.melon.rpc.ManageJobRequestMetadata}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.toutiao.melon.rpc.ManageJobRequestMetadata)
      ManageJobRequestMetadataOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Master.internal_static_com_toutiao_melon_rpc_ManageJobRequestMetadata_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Master.internal_static_com_toutiao_melon_rpc_ManageJobRequestMetadata_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ManageJobRequestMetadata.class, Builder.class);
    }

    // Construct using com.toutiao.melon.rpc.ManageJobRequestMetadata.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @Override
    public Builder clear() {
      super.clear();
      requestType_ = 0;

      jobName_ = "";

      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return Master.internal_static_com_toutiao_melon_rpc_ManageJobRequestMetadata_descriptor;
    }

    @Override
    public ManageJobRequestMetadata getDefaultInstanceForType() {
      return ManageJobRequestMetadata.getDefaultInstance();
    }

    @Override
    public ManageJobRequestMetadata build() {
      ManageJobRequestMetadata result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public ManageJobRequestMetadata buildPartial() {
      ManageJobRequestMetadata result = new ManageJobRequestMetadata(this);
      result.requestType_ = requestType_;
      result.jobName_ = jobName_;
      onBuilt();
      return result;
    }

    @Override
    public Builder clone() {
      return super.clone();
    }
    @Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.setField(field, value);
    }
    @Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.addRepeatedField(field, value);
    }
    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof ManageJobRequestMetadata) {
        return mergeFrom((ManageJobRequestMetadata)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(ManageJobRequestMetadata other) {
      if (other == ManageJobRequestMetadata.getDefaultInstance()) return this;
      if (other.requestType_ != 0) {
        setRequestTypeValue(other.getRequestTypeValue());
      }
      if (!other.getJobName().isEmpty()) {
        jobName_ = other.jobName_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      ManageJobRequestMetadata parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (ManageJobRequestMetadata) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int requestType_ = 0;
    /**
     * <code>.com.toutiao.melon.rpc.ManageJobRequestMetadata.RequestType request_type = 1;</code>
     * @return The enum numeric value on the wire for requestType.
     */
    public int getRequestTypeValue() {
      return requestType_;
    }
    /**
     * <code>.com.toutiao.melon.rpc.ManageJobRequestMetadata.RequestType request_type = 1;</code>
     * @param value The enum numeric value on the wire for requestType to set.
     * @return This builder for chaining.
     */
    public Builder setRequestTypeValue(int value) {
      requestType_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.com.toutiao.melon.rpc.ManageJobRequestMetadata.RequestType request_type = 1;</code>
     * @return The requestType.
     */
    public RequestType getRequestType() {
      @SuppressWarnings("deprecation")
      RequestType result = RequestType.valueOf(requestType_);
      return result == null ? RequestType.UNRECOGNIZED : result;
    }
    /**
     * <code>.com.toutiao.melon.rpc.ManageJobRequestMetadata.RequestType request_type = 1;</code>
     * @param value The requestType to set.
     * @return This builder for chaining.
     */
    public Builder setRequestType(RequestType value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      requestType_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.com.toutiao.melon.rpc.ManageJobRequestMetadata.RequestType request_type = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearRequestType() {
      
      requestType_ = 0;
      onChanged();
      return this;
    }

    private Object jobName_ = "";
    /**
     * <code>string job_name = 2;</code>
     * @return The jobName.
     */
    public String getJobName() {
      Object ref = jobName_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        jobName_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string job_name = 2;</code>
     * @return The bytes for jobName.
     */
    public com.google.protobuf.ByteString
        getJobNameBytes() {
      Object ref = jobName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        jobName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string job_name = 2;</code>
     * @param value The jobName to set.
     * @return This builder for chaining.
     */
    public Builder setJobName(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      jobName_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string job_name = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearJobName() {
      
      jobName_ = getDefaultInstance().getJobName();
      onChanged();
      return this;
    }
    /**
     * <code>string job_name = 2;</code>
     * @param value The bytes for jobName to set.
     * @return This builder for chaining.
     */
    public Builder setJobNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      jobName_ = value;
      onChanged();
      return this;
    }
    @Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.toutiao.melon.rpc.ManageJobRequestMetadata)
  }

  // @@protoc_insertion_point(class_scope:com.toutiao.melon.rpc.ManageJobRequestMetadata)
  private static final ManageJobRequestMetadata DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new ManageJobRequestMetadata();
  }

  public static ManageJobRequestMetadata getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ManageJobRequestMetadata>
      PARSER = new com.google.protobuf.AbstractParser<ManageJobRequestMetadata>() {
    @Override
    public ManageJobRequestMetadata parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ManageJobRequestMetadata(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ManageJobRequestMetadata> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<ManageJobRequestMetadata> getParserForType() {
    return PARSER;
  }

  @Override
  public ManageJobRequestMetadata getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

