// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: com/toutiao/melon/rpc/master.proto

package com.toutiao.melon.rpc;

public final class Master {
  private Master() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_toutiao_melon_rpc_ManageJobRequestMetadata_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_toutiao_melon_rpc_ManageJobRequestMetadata_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_toutiao_melon_rpc_ManageJobRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_toutiao_melon_rpc_ManageJobRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_toutiao_melon_rpc_ManageJobResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_toutiao_melon_rpc_ManageJobResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_toutiao_melon_rpc_ProvideJarRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_toutiao_melon_rpc_ProvideJarRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_toutiao_melon_rpc_ProvideJarResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_toutiao_melon_rpc_ProvideJarResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\"com/toutiao/melon/rpc/master.proto\022\025co" +
      "m.toutiao.melon.rpc\"\302\001\n\030ManageJobRequest" +
      "Metadata\022Q\n\014request_type\030\001 \001(\0162;.com.tou" +
      "tiao.melon.rpc.ManageJobRequestMetadata." +
      "RequestType\022\020\n\010job_name\030\002 \001(\t\"A\n\013Request" +
      "Type\022\r\n\tSTART_Job\020\000\022\014\n\010STOP_Job\020\001\022\025\n\021QUE" +
      "RY_RUNNING_Job\020\002\"t\n\020ManageJobRequest\022C\n\010" +
      "metadata\030\001 \001(\0132/.com.toutiao.melon.rpc.M" +
      "anageJobRequestMetadataH\000\022\023\n\tjar_bytes\030\002" +
      " \001(\014H\000B\006\n\004data\"$\n\021ManageJobResponse\022\017\n\007m" +
      "essage\030\001 \001(\t\"%\n\021ProvideJarRequest\022\020\n\010job" +
      "_name\030\001 \001(\t\"D\n\022ProvideJarResponse\022\023\n\tjar" +
      "_bytes\030\001 \001(\014H\000\022\021\n\007message\030\002 \001(\tH\000B\006\n\004dat" +
      "a2o\n\tManageJob\022b\n\tManageJob\022\'.com.toutia" +
      "o.melon.rpc.ManageJobRequest\032(.com.touti" +
      "ao.melon.rpc.ManageJobResponse\"\000(\0012s\n\nPr" +
      "ovideJar\022e\n\nProvideJar\022(.com.toutiao.mel" +
      "on.rpc.ProvideJarRequest\032).com.toutiao.m" +
      "elon.rpc.ProvideJarResponse\"\0000\001B\002P\001b\006pro" +
      "to3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_toutiao_melon_rpc_ManageJobRequestMetadata_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_toutiao_melon_rpc_ManageJobRequestMetadata_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_toutiao_melon_rpc_ManageJobRequestMetadata_descriptor,
        new String[] { "RequestType", "JobName", });
    internal_static_com_toutiao_melon_rpc_ManageJobRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_toutiao_melon_rpc_ManageJobRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_toutiao_melon_rpc_ManageJobRequest_descriptor,
        new String[] { "Metadata", "JarBytes", "Data", });
    internal_static_com_toutiao_melon_rpc_ManageJobResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_toutiao_melon_rpc_ManageJobResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_toutiao_melon_rpc_ManageJobResponse_descriptor,
        new String[] { "Message", });
    internal_static_com_toutiao_melon_rpc_ProvideJarRequest_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_com_toutiao_melon_rpc_ProvideJarRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_toutiao_melon_rpc_ProvideJarRequest_descriptor,
        new String[] { "JobName", });
    internal_static_com_toutiao_melon_rpc_ProvideJarResponse_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_com_toutiao_melon_rpc_ProvideJarResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_toutiao_melon_rpc_ProvideJarResponse_descriptor,
        new String[] { "JarBytes", "Message", "Data", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
