// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: com/toutiao/melon/rpc/master.proto

package com.toutiao.melon.rpc;

public interface ProvideJarRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.toutiao.melon.rpc.ProvideJarRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string job_name = 1;</code>
   * @return The jobName.
   */
  String getJobName();
  /**
   * <code>string job_name = 1;</code>
   * @return The bytes for jobName.
   */
  com.google.protobuf.ByteString
      getJobNameBytes();
}
