// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: com/toutiao/melon/rpc/worker.proto

package com.toutiao.melon.rpc;

public interface RpcEventOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.toutiao.melon.rpc.RpcEvent)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bytes event_bytes = 1;</code>
   * @return The eventBytes.
   */
  com.google.protobuf.ByteString getEventBytes();
}
