// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: com/toutiao/melon/rpc/worker.proto

package com.toutiao.melon.rpc;

public final class Worker {
  private Worker() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_toutiao_melon_rpc_RpcEvent_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_toutiao_melon_rpc_RpcEvent_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\"com/toutiao/melon/rpc/worker.proto\022\025co" +
      "m.toutiao.melon.rpc\032\033google/protobuf/emp" +
      "ty.proto\"\037\n\010RpcEvent\022\023\n\013event_bytes\030\001 \001(" +
      "\0142[\n\rTransmitEvent\022J\n\rTransmitEvent\022\037.co" +
      "m.toutiao.melon.rpc.RpcEvent\032\026.google.pr" +
      "otobuf.Empty\"\000B\002P\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.EmptyProto.getDescriptor(),
        });
    internal_static_com_toutiao_melon_rpc_RpcEvent_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_toutiao_melon_rpc_RpcEvent_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_toutiao_melon_rpc_RpcEvent_descriptor,
        new String[] { "EventBytes", });
    com.google.protobuf.EmptyProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
